// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	"professional-portfolio-kv": KVNamespace;
	R2: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
