/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradieRouteImport } from './routes/tradie'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as ItHelpDeskRouteImport } from './routes/it-help-desk'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GradeCalculatorRouteImport } from './routes/grade-calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedEditorIndexRouteImport } from './routes/_authenticated/editor/index'
import { Route as AuthenticatedEditorSlugRouteImport } from './routes/_authenticated/editor/$slug'

const TradieRoute = TradieRouteImport.update({
  id: '/tradie',
  path: '/tradie',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ItHelpDeskRoute = ItHelpDeskRouteImport.update({
  id: '/it-help-desk',
  path: '/it-help-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeCalculatorRoute = GradeCalculatorRouteImport.update({
  id: '/grade-calculator',
  path: '/grade-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorIndexRoute =
  AuthenticatedEditorIndexRouteImport.update({
    id: '/editor/',
    path: '/editor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditorSlugRoute = AuthenticatedEditorSlugRouteImport.update({
  id: '/editor/$slug',
  path: '/editor/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grade-calculator': typeof GradeCalculatorRoute
  '/home': typeof HomeRoute
  '/it-help-desk': typeof ItHelpDeskRoute
  '/navigation': typeof NavigationRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/tradie': typeof TradieRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/editor/$slug': typeof AuthenticatedEditorSlugRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/grade-calculator': typeof GradeCalculatorRoute
  '/home': typeof HomeRoute
  '/it-help-desk': typeof ItHelpDeskRoute
  '/navigation': typeof NavigationRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/tradie': typeof TradieRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/editor/$slug': typeof AuthenticatedEditorSlugRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/grade-calculator': typeof GradeCalculatorRoute
  '/home': typeof HomeRoute
  '/it-help-desk': typeof ItHelpDeskRoute
  '/navigation': typeof NavigationRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/tradie': typeof TradieRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/editor/$slug': typeof AuthenticatedEditorSlugRoute
  '/_authenticated/editor/': typeof AuthenticatedEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/grade-calculator'
    | '/home'
    | '/it-help-desk'
    | '/navigation'
    | '/resume-builder'
    | '/tradie'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/blog/$slug'
    | '/editor/$slug'
    | '/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/grade-calculator'
    | '/home'
    | '/it-help-desk'
    | '/navigation'
    | '/resume-builder'
    | '/tradie'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/blog/$slug'
    | '/editor/$slug'
    | '/editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/grade-calculator'
    | '/home'
    | '/it-help-desk'
    | '/navigation'
    | '/resume-builder'
    | '/tradie'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/blog/$slug'
    | '/_authenticated/editor/$slug'
    | '/_authenticated/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  GradeCalculatorRoute: typeof GradeCalculatorRoute
  HomeRoute: typeof HomeRoute
  ItHelpDeskRoute: typeof ItHelpDeskRoute
  NavigationRoute: typeof NavigationRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  TradieRoute: typeof TradieRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tradie': {
      id: '/tradie'
      path: '/tradie'
      fullPath: '/tradie'
      preLoaderRoute: typeof TradieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-help-desk': {
      id: '/it-help-desk'
      path: '/it-help-desk'
      fullPath: '/it-help-desk'
      preLoaderRoute: typeof ItHelpDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-calculator': {
      id: '/grade-calculator'
      path: '/grade-calculator'
      fullPath: '/grade-calculator'
      preLoaderRoute: typeof GradeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/': {
      id: '/_authenticated/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor/$slug': {
      id: '/_authenticated/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof AuthenticatedEditorSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedEditorSlugRoute: typeof AuthenticatedEditorSlugRoute
  AuthenticatedEditorIndexRoute: typeof AuthenticatedEditorIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedEditorSlugRoute: AuthenticatedEditorSlugRoute,
  AuthenticatedEditorIndexRoute: AuthenticatedEditorIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  GradeCalculatorRoute: GradeCalculatorRoute,
  HomeRoute: HomeRoute,
  ItHelpDeskRoute: ItHelpDeskRoute,
  NavigationRoute: NavigationRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  TradieRoute: TradieRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
